---
- name: Show VPC File Share mappings
  ansible.builtin.debug:
    msg: "{{ item.key }}: {{ item.value }}"
  with_dict: "{{ name_mount_path_map }}"

- name: Show NFS Share mappings
  ansible.builtin.debug:
    msg: "{{ item.key }}: {{ item.value }}"
  with_dict: "{{ all_nfs_shares_map }}"

- name: Create base directories for VPC File shares
  file:
    path: "/mnt/{{ item.key }}"
    state: directory
    mode: '0777'
  with_dict: "{{ name_mount_path_map }}"

- name: Add NFS entries to /etc/fstab for VPC File shares
  lineinfile:
    path: /etc/fstab
    line: "{{ item.value }} /mnt/{{ item.key }} nfs rw,sec=sys,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0"
    state: present
    create: yes
  with_dict: "{{ name_mount_path_map }}"
  notify: Mount NFS

- name: Create base directories for all NFS mount points
  file:
    path: "/mnt/{{ item.key }}"
    state: directory
    mode: '0777'
  with_dict: "{{ all_nfs_shares_map }}"

- name: Mount NFS shares
  ansible.builtin.mount:
    path: "/mnt/{{ item.key }}"
    src: "{{ item.value }}"
    fstype: nfs
    opts: rw,sec=sys,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev
    state: mounted
  with_dict: "{{ all_nfs_shares_map }}"

- name: Flush handlers immediately
  meta: flush_handlers

- name: Verify mounted filesystems
  command: df -h
  register: df_output
  changed_when: false
  failed_when: df_output.rc != 0

- name: Check directory listing
  command: ls -ltr /mnt/lsf
  register: ls_output
  changed_when: false
  failed_when: ls_output.rc != 0
