---
  - name: Check if LSF installer directory exists
    ansible.builtin.stat:
      path: "{{ ansible_tool_kit_path }}"
    register: toolkit_path

  - name: Fail if LSF installer directory does not exist
    ansible.builtin.fail:
      msg: "ERROR: Directory {{ ansible_tool_kit_path }} does not exist. Please ensure the IBM LSF installer toolkit is present."
    when: not toolkit_path.stat.exists

  - name: Insert stream_dir setup after JDBC export
    ansible.builtin.replace:
      path: "{{ ansible_tool_kit_path }}/roles/deploy-gui/tasks/install_pac.yml"
      regexp: '^( *export MYSQL_JDBC_DRIVER_JAR=.*)$'
      replace: '\1\n{{ insert_lines | regex_replace("\n", "\\n") | regex_replace("\r", "") }}'
    when: toolkit_path.stat.exists

  - name: Comment stat_js_conf line
    ansible.builtin.replace:
      path: "{{ ansible_tool_kit_path }}/roles/deploy-gui/tasks/configure_master.yml"
      regexp: '^\s*- stat_js_conf\.stat\.exists\s*==\s*True'
      replace: '# - stat_js_conf.stat.exists == True'
    when: toolkit_path.stat.exists

  - name: Comment out setup_sharedir_ppm task block
    ansible.builtin.replace:
      path: "{{ ansible_tool_kit_path }}/roles/deploy-gui/tasks/post_deploy_primary.yml"
      regexp: |
        (?m)^(\s*)- include_tasks: setup_sharedir_ppm\.yml\n\1  when:\n\1    - lsf_shared_dir != "none"\n\1    - LSF_SUITE_EDITION != 'LSF Suite for Workgroup'
      replace: |
        \1# - include_tasks: setup_sharedir_ppm.yml
        \1#   when:
        \1#     - lsf_shared_dir != "none"
        \1#     - LSF_SUITE_EDITION != 'LSF Suite for Workgroup'
    when: toolkit_path.stat.exists

  - name: Comment out Configure PM Common script block
    ansible.builtin.replace:
      path: "{{ ansible_tool_kit_path }}/roles/deploy-lsf-clients/tasks/main.yml"
      regexp: |
        (?m)^(\s*)- name: Call the Configure PM Common script\n\1  include_tasks: \.\./\.\./deploy-gui/tasks/configure_pm_common\.yml\n\1  when:\n\1    - nfs_deployment == False\n\1    - LSF_SUITE_EDITION != 'LSF Suite for Workgroup'\n\1    - groups\.GUI_Hosts \| length > 0\n\1    - inventory_hostname not in groups\.GUI_Hosts
      replace: |
        \1# - name: Call the Configure PM Common script
        \1#   include_tasks: ../../deploy-gui/tasks/configure_pm_common.yml
        \1#   when:
        \1#     - nfs_deployment == False
        \1#     - LSF_SUITE_EDITION != 'LSF Suite for Workgroup'
        \1#     - groups.GUI_Hosts | length > 0
        \1#     - inventory_hostname not in groups.GUI_Hosts
    when: toolkit_path.stat.exists