# Ensure provisioned VMs are up and Passwordless SSH setup has been established

- name: Connect to remote hosts via bastion and perform tasks
  hosts: [all_nodes]
  any_errors_fatal: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: >
      -o ProxyJump=ubuntu@150.239.87.117
      -o ControlMaster=auto
      -o ControlPersist=30m
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
    ansible_user: root
    ansible_ssh_private_key_file: ./../../modules/ansible-roles/storage_id_rsa
  tasks:
    - name: Check passwordless SSH on all scale inventory hosts
      shell: echo PASSWDLESS_SSH_ENABLED
      register: result
      until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
      retries: 60
      delay: 10

- name: Prerequisite Configuration
  hosts: [all_nodes]
  any_errors_fatal: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: >
      -o ProxyJump=ubuntu@150.239.87.117
      -o ControlMaster=auto
      -o ControlPersist=30m
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
    ansible_user: root
    ansible_ssh_private_key_file: ./../../modules/ansible-roles/storage_id_rsa
  roles:
     - prerequisite

- name: Cloud Logs Configuration
  hosts: [all_nodes]
  any_errors_fatal: true
  gather_facts: true
  vars:
    ansible_ssh_common_args: >
      -o ProxyJump=ubuntu@150.239.87.117
      -o ControlMaster=auto
      -o ControlPersist=30m
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
    ansible_user: root
    ansible_ssh_private_key_file: ./../../modules/ansible-roles/storage_id_rsa
  roles:
    - { role: cloudlogs, tags: ["cloud_logs"] }    

- name: Cloud Monitoring Configuration
  hosts: [all_nodes]
  any_errors_fatal: true
  gather_facts: true
  vars:
    ansible_ssh_common_args: >
      -o ProxyJump=ubuntu@150.239.87.117
      -o ControlMaster=auto
      -o ControlPersist=30m
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
    ansible_user: root
    ansible_ssh_private_key_file: ./../../modules/ansible-roles/storage_id_rsa
  roles:
    - { role: cloudmonitoring, tags: ["cloud_monitoring"] }        
