---
- name: Check if observability logs for management are enabled
  ansible.builtin.debug:
    msg: "Configuring cloud logs for management since observability logs for management is enabled"
  when: logs_enable_for_management | bool

- name: Copy post-config.sh script
  ansible.builtin.copy:
    src: /root/post-config.sh
    dest: /opt/ibm/post-config.sh
    mode: '0755'
    remote_src: true
  when: logs_enable_for_management | bool

- name: Create fluent-bit.conf for cloud logs
  ansible.builtin.copy:
    dest: /etc/fluent-bit/fluent-bit.conf
    content: |
      [SERVICE]
        Flush                   1
        Log_Level               info
        Daemon                  off
        Parsers_File            parsers.conf
        Plugins_File            plugins.conf
        HTTP_Server             On
        HTTP_Listen             0.0.0.0
        HTTP_Port               8081
        Health_Check            On
        HC_Errors_Count         1
        HC_Retry_Failure_Count  1
        HC_Period               30
        storage.path            /fluent-bit/cache
        storage.max_chunks_up   192
        storage.metrics         On
      [INPUT]
        Name                syslog
        Path                /tmp/in_syslog
        Buffer_Chunk_Size   32000
        Buffer_Max_Size     64000
        Receive_Buffer_Size 512000
      [INPUT]
        Name              tail
        Tag               *
        Path              /opt/ibm/lsf/log/*.log
        Path_Key          file
        Exclude_Path      /var/log/at/**
        DB                /opt/ibm/lsf/log/fluent-bit.DB
        Buffer_Chunk_Size 32KB
        Buffer_Max_Size   256KB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
        storage.pause_on_chunks_overlimit on
      [FILTER]
        Name modify
        Match *
        Add subsystemName management
        Add applicationName lsf
      @INCLUDE output-logs-router-agent.conf
  when: logs_enable_for_management | bool

- name: Ensure VPC_API_KEY is set
  ansible.builtin.set_fact:
    VPC_API_KEY: "{{ lookup('env', 'VPC_API_KEY') }}"
  when: lookup('env', 'VPC_API_KEY') is defined and lookup('env', 'VPC_API_KEY') | length > 0

- name: Fetch API KEY from environmental variable of Ansible controller
  ansible.builtin.shell: "echo $VPC_API_KEY"
  register: env_api_key
  changed_when: false

- name: Debug API Key
  ansible.builtin.debug:
    msg: "API Key is {{ env_api_key.stdout }}"
  when: logs_enable_for_management | bool    

- name: Run post-config.sh script
  ansible.builtin.command: >
    /opt/ibm/post-config.sh -h {{ cloud_logs_ingress_private_endpoint }}
    -p "3443"
    -t "/logs/v1/singles"
    -a IAMAPIKey
    -k {{ env_api_key.stdout }}
    --send-directly-to-icl
    -s true
    -i Production
  when: logs_enable_for_management | bool and env_api_key.stdout | length > 0

- name: Test cloud logs configuration
  ansible.builtin.shell: |
    echo "INFO Testing IBM Cloud LSF Logs from management: {{ ansible_hostname }}" >> /opt/ibm/lsf/log/test.log
  when: logs_enable_for_management | bool
