---
# Restart the NetworkManager on deployer node

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
  delegate_to: "{{ lsf_deployer_hostname }}.{{ compute_dns_name }}"
  run_once: true

# Installing required prerequisite packages for the LSF cluster creation.

- name: LSF | Check OS version for package installation
  ansible.builtin.shell: "grep -oE 'release [0-9]+' /etc/redhat-release | awk '{print $2}'"
  register: rhel_version
  changed_when: false

- name: LSF | Install Required Packages
  ansible.builtin.dnf:
    name:
      - lsof
      - ipmitool
    state: present
  when: rhel_version.stdout in ["8", "9"]

# Create the shared lsf directory

- name: Display the last directory
  debug:
    msg: "The last directory is: {{ lsf_dir }}"

- name: Create base directories for lsf configuration
  file:
    path: "/mnt/lsf/{{ lsf_dir }}"
    state: directory
    mode: "0777"

# NetworkManager status check
- name: Check NetworkManager status
  ansible.builtin.command: systemctl is-active NetworkManager
  register: nm_status
  delegate_to: "{{ lsf_deployer_hostname }}.{{ compute_dns_name }}"
  run_once: true

# NetworkManager not in active, again restart
- name: Restart NetworkManager if not active
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
  delegate_to: "{{ lsf_deployer_hostname }}.{{ compute_dns_name }}"
  when: nm_status.stdout != 'active'
  run_once: true
